id: I029541A9
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:48.821526
last_modified: 2023-01-04 11:30:48.821538
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  FE2E:
    title: Introduction to The Excellent Path of Devotion
    base_file: FE2E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
